/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  theme: {
    extend: {
      colors: {
        blue: '#2DA4FF',
        blue_dark: '#116DB3',
        blue_light_0:'#E9F5FF',
        blue_light_1:'#D5EDFF',
        blue_light_2:'#ABDBFF',
        blue_light_3:'#81C8FF',
        yellow: '#D5EDFF',
        yellow_dark: '#C9A219',
        yellow_light_3: '#FFDE68',
        yellow_light_2: '#FFE99A',
        yellow_light_1: '#FFF4CD',
        orange:'#FF8B1F',
        orange_dark: '#D46D0E',
        orange_light_3: '#FFB979',
        orange_light_2: '#FFB979',
        orange_light_1: '#FFE8D2',
        navy: '#162F70',
        navy_dark: '#071E5D',
        navy_light_3: '#5C6E9B',
        navy_light_2: '#8A96B7',
        navy_light_1: '#D0D5E2',
        gray_dark_1 : '#4E4F54',
        gray_dark_2 : '#171717',
        gray: '#949499',
        gray_light_1: '#F9F9FB',
        gray_light_2: '#F4F4F4',
        gray_light_3: '#E1E2E3',
        bg_white: '#F9F8F8',
        white: '#FFFFFF',
      },
    },
  },
  plugins: [],
};
