// export { default as logoColor } from './logo-color.png';
export { default as defaultImageBlack } from './user-profile-default-black-100x100.png';
export { default as defaultImageGray } from './user-profile-default-gray-100x100.png';
export { default as signOutDropDown } from './btn-logout-dropdown-w-contents.png';
export { default as test1 } from './test1.png';
export { default as test2 } from './test2.png';
export { default as test3 } from './test3.png';
export { default as defaultMainPlan } from './main-background-default-plan-250x200.png';
export { default as logoColor } from './img-traduler-logo-color-4x.png';
export { default as logoWhite } from './img-traduler-logo-white-4x.png';
